/*
 * Copyright (c) 2019 Repackage Tests Maven Plugin
 * project contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.l2x6.rpkgtests;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;

import org.junit.Assert;
import org.junit.Test;

public class GenerateTestModulesMojoTest {
    private static final String eol = "\n";
    private static final String indent = "  ";

    @Test
    public void addModules() {
        assertAddModules(
                "<project>" + eol //
                        + indent + "<artifactId />" + eol //
                        + "</project>",
                "<project>" + eol //
                        + indent + "<artifactId />" + eol //
                        + indent + "<modules>" + eol //
                        + indent + indent + "<!-- START: modules generated by rpkgtests-maven-plugin -->" + eol //
                        + indent + indent + "<module>m1</module>" + eol //
                        + indent + indent + "<module>m2</module>" + eol //
                        + indent + indent + "<!-- END: modules generated by rpkgtests-maven-plugin -->" + eol //
                        + indent + "</modules>" + eol //
                        + "</project>");

        assertAddModules(
                "<project>" + eol //
                        + indent + "<artifactId />" + eol //
                        + indent + "<modules>" + eol //
                        + indent + "</modules>" + eol //
                        + "</project>",
                "<project>" + eol //
                        + indent + "<artifactId />" + eol //
                        + indent + "<modules>" + eol //
                        + indent + indent + "<!-- START: modules generated by rpkgtests-maven-plugin -->" + eol //
                        + indent + indent + "<module>m1</module>" + eol //
                        + indent + indent + "<module>m2</module>" + eol //
                        + indent + indent + "<!-- END: modules generated by rpkgtests-maven-plugin -->" + eol //
                        + indent + "</modules>" + eol //
                        + "</project>");

        assertAddModules(
                "<project>" + eol //
                        + indent + "<artifactId />" + eol //
                        + indent + "<modules>" + eol //
                        + indent + indent + "<module>old-m1</module>" + eol //
                        + indent + indent + "<module>old-m2</module>" + eol //
                        + indent + "</modules>" + eol //
                        + "</project>",
                "<project>" + eol //
                        + indent + "<artifactId />" + eol //
                        + indent + "<modules>" + eol //
                        + indent + indent + "<!-- START: modules generated by rpkgtests-maven-plugin -->" + eol //
                        + indent + indent + "<module>m1</module>" + eol //
                        + indent + indent + "<module>m2</module>" + eol //
                        + indent + indent + "<!-- END: modules generated by rpkgtests-maven-plugin -->" + eol //
                        + indent + indent + "<module>old-m1</module>" + eol //
                        + indent + indent + "<module>old-m2</module>" + eol //
                        + indent + "</modules>" + eol //
                        + "</project>");

        assertAddModules(
                "<project>" + eol //
                        + indent + "<artifactId />" + eol //
                        + indent + "<modules>" + eol //
                        + indent + indent + "<module>old-m1</module>" + eol //
                        + indent + indent + "<module>old-m2</module>" + eol //
                        + indent + indent + "<!-- START: modules generated by rpkgtests-maven-plugin -->" + eol //
                        + indent + indent + "<module>foo1</module>" + eol //
                        + indent + indent + "<module>foo2</module>" + eol //
                        + indent + indent + "<!-- END: modules generated by rpkgtests-maven-plugin -->" + eol //
                        + indent + "</modules>" + eol //
                        + "</project>",

                "<project>" + eol //
                        + indent + "<artifactId />" + eol //
                        + indent + "<modules>" + eol //
                        + indent + indent + "<module>old-m1</module>" + eol //
                        + indent + indent + "<module>old-m2</module>" + eol //
                        + indent + indent + "<!-- START: modules generated by rpkgtests-maven-plugin -->" + eol //
                        + indent + indent + "<module>m1</module>" + eol //
                        + indent + indent + "<module>m2</module>" + eol //
                        + indent + indent + "<!-- END: modules generated by rpkgtests-maven-plugin -->" + eol //
                        + indent + "</modules>" + eol //
                        + "</project>");

    }

    void assertAddModules(String input, String expected) {
        final List<String> modules = Arrays.asList("m1", "m2");
        final Path p = Paths.get("pom.xml");
        final String actual = GenerateTestModulesMojo.addModules(input, p, modules);
        Assert.assertEquals(expected, actual);
    }

}
